import prompts
from base import callLLM
from logger_config import get_logger

# Get the configured logger
logger = get_logger()
def Transition(sectionA, sectionB, textA, textB):
    prompt = prompts.Transition_transition_PROMPT
    prompt = prompt.format(sectionA =sectionA, sectionB=sectionB, textA=textA, textB=textB)
    logger.info("transitional Prompt:" + prompt)
    response = callLLM(prompt)
    logger.info("transitional Response:" + response)
    #return response.split('\n')[-1]
    return response


def Add_transition(outline, content):
    last_paragraph = ""
    for current_paragraph in outline.strip().split('\n'):
        if last_paragraph == "" or content[last_paragraph] == []:
            last_paragraph = current_paragraph
            continue
        if content[current_paragraph] == []:
            continue
        result = Transition(last_paragraph, current_paragraph, content[last_paragraph][-1],
                            content[current_paragraph][0])
        content[current_paragraph][0] = result
        last_paragraph = current_paragraph
    return content

if __name__ == "__main__":
    # Input text
    outline = """## 1. Introduction: Brief introduction to 'Interstellar'
### 1.1. Genre of 'Interstellar'
### 1.2. Director of 'Interstellar'
### 1.3. Release date of 'Interstellar'
## 2. Summary of the plot of 'Interstellar'
## 3. Christopher Nolan's Previous Works and Their Influence on 'Interstellar'
## 4. Critical Reception of 'Interstellar'
### 4.1. Awards Won by 'Interstellar'
### 4.2. Notable Reviews and Criticisms
## 5. Box Office Performance and Audience Reception
## 6. Conclusion: Why 'Interstellar' is a Significant Film in Modern Cinema"""
    content = {"## 1. Introduction: Brief introduction to 'Interstellar'": '',
               "### 1.1. Genre of 'Interstellar'": [
                   '"Interstellar" is a groundbreaking science-fiction film that masterfully blends awe-inspiring visuals with profound human drama. Directed by Christopher Nolan, the film transcends traditional genre boundaries by integrating cutting-edge science with deeply emotional narratives. This fusion creates a unique cinematic experience that captivates both the intellect and the heart. For instance, the scene where Cooper communicates with his daughter through time via gravitational waves exemplifies the film\'s exploration of themes such as love, sacrifice, and the human spirit of exploration. This elevates "Interstellar" beyond mere space adventure, making it a thought-provoking and emotionally resonant masterpiece. Nolan\'s meticulous attention to scientific detail, combined with his innovative storytelling techniques, ensures that "Interstellar" remains accessible and engaging despite its complexity. The result is a genre-defying epic that challenges audiences to ponder the mysteries of the universe while deeply connecting with its characters\' journeys.'],
               "### 1.2. Director of 'Interstellar'": [
                   'Christopher Nolan, the visionary behind "Interstellar," has crafted a film that transcends conventional storytelling. His direction seamlessly blends visionary science-fiction with profound human drama, setting a new standard for the genre. Nolan\'s meticulous attention to detail, from awe-inspiring visuals to intricate plotlines, ensures that "Interstellar" remains a deeply resonant cinematic experience. The film\'s exploration of themes such as love, time, and human resilience is not just a narrative device but a philosophical journey that challenges viewers to ponder the mysteries of existence.',
                   'Nolan\'s collaboration with theoretical physicist Kip Thorne adds an unprecedented level of scientific authenticity to the film. This partnership ensures that even the most complex scientific concepts are depicted with accuracy and clarity, making "Interstellar" not only a visual spectacle but also an intellectually stimulating endeavor. For instance, the depiction of black holes and wormholes in the film is grounded in real scientific theories, enhancing its credibility and appeal to both scientists and moviegoers. The director\'s commitment to practical effects and real models for spacecraft further enhances the film\'s immersive quality, transporting viewers into the vastness of space with unparalleled realism.',
                   'The emotional depth in "Interstellar" is equally compelling, driven by stellar performances from actors like Matthew McConaughey and Anne Hathaway. McConaughey\'s portrayal of Cooper is both powerful and nuanced, capturing the character\'s emotional journey with authenticity. For example, his scenes conveying Cooper\'s longing for his family on Earth are particularly poignant. Hathaway\'s Amelia Brand complements this with her own complex emotions and determination, creating a dynamic interplay between characters that enriches the narrative. The bond between Cooper and his daughter Murph, portrayed at different stages by Jessica Chastain and Mackenzie Foy, adds another layer of emotional resonance to the story—particularly in scenes where Murph communicates her frustration with her father through binary code messages across vast distances in space.',
                   'Nolan\'s ability to weave together these elements—science fiction grandeur with intimate human drama—elevates "Interstellar" beyond mere entertainment into a thought-provoking exploration of humanity\'s place in the universe. The film continues to inspire discussions among scientists and moviegoers alike long after its initial release, cementing its legacy as a modern cinematic masterpiece. Its impact is evident in how it has sparked conversations about theoretical physics concepts like relativity and quantum mechanics among general audiences who might not have engaged with these topics otherwise.'],
               "### 1.3. Release date of 'Interstellar'": [
                   'The release date of "Interstellar" is November 7, 2014. Directed by Christopher Nolan, this sci-fi epic captivated audiences with its blend of scientific authenticity and emotional depth. The film follows Joseph Cooper, played by Matthew McConaughey, a former NASA pilot turned farmer who is tasked with leading a mission to find a new habitable planet for humanity. Alongside Cooper are Dr. Amelia Brand (Anne Hathaway) and other crew members, including Professor John Brand (Michael Caine). Professor Brand has devised two plans to save humanity: Plan A involves solving the gravitational theory to enable large-scale space travel, while Plan B focuses on colonizing another planet through human reproduction.',
                   "As the crew ventures through wormholes and explores distant planets, they encounter time dilation effects that complicate their mission. One notable example is when Cooper experiences significant time dilation on Miller's planet, where hours feel like years back on Earth. This effect underscores the emotional stakes of their journey. Cooper's relationship with his daughter Murph (played by Jessica Chastain and Mackenzie Foy) becomes a central theme, highlighting the emotional stakes of their interstellar journey.",
                   "The film's climax occurs when Cooper is ejected from a tesseract and wakes up on a space habitat orbiting Saturn. There, he reunites with an elderly Murph on her deathbed. Using the quantum data he sent back in time, Murph has solved the gravitational theory for Plan A, enabling humanity's exodus from Earth. Cooper then sets off to join Brand on Edmunds' planet to establish a new human colony.",
                   '"Interstellar" is not just a science fiction film; it is a profound exploration of love, sacrifice, and the human spirit\'s resilience in the face of existential threats. Its complex narrative structure and deep philosophical questions make it a cinematic experience that resonates long after the credits roll.'],
               "## 2. Summary of the plot of 'Interstellar'": [
                   'Christopher Nolan\'s "Interstellar" is not just a film about space exploration; it\'s a profound meditation on the human condition. The movie delves into the complexities of time, love, and survival, all set against the backdrop of a dying Earth. Matthew McConaughey\'s character, Cooper, embarks on a mission through a wormhole to find a new home for humanity. This journey allows the film to explore how love can transcend the boundaries of time and space. One particularly poignant moment is the bookshelf scene, where Cooper communicates with his daughter Murph across different dimensions of time. To fully appreciate this scene, it\'s important to understand its context within the broader themes of the film. "Interstellar" challenges viewers to reconsider their understanding of existence and the power of human connection. Through its intricate plot and deep character development, "Interstellar" offers a compelling narrative that blends scientific theory with emotional depth, making it a cinematic masterpiece that resonates long after the credits roll.'],
               "## 3. Christopher Nolan's Previous Works and Their Influence on 'Interstellar'": [
                   'Christopher Nolan\'s "Interstellar" is not just a film; it\'s a cinematic event that redefined the boundaries of science fiction. Drawing from his previous works like "Memento" and "Inception," Nolan\'s ability to blend complex narrative structures with profound emotional depth is evident in "Interstellar." The film\'s journey through space and time, coupled with its exploration of human resilience and love, sets it apart as a masterpiece.',
                   "Nolan's approach to filmmaking, characterized by his preference for practical effects over CGI, adds a layer of authenticity to the film. This commitment to realism is mirrored in the scientific rigor that underpins the story. Physicists like Kip Thorne were consulted to ensure that the film's depiction of black holes and wormholes was scientifically plausible, enhancing its credibility and appeal to both science enthusiasts and casual viewers.",
                   'Transitioning to its emotional core, "Interstellar" portrays human relationships against the backdrop of cosmic exploration. The bond between Cooper (Matthew McConaughey) and his daughter Murph (Jessica Chastain) serves as the linchpin of the narrative, driving home themes of sacrifice and hope. This familial connection not only grounds the story but also elevates it beyond mere spectacle, making it one of Nolan\'s most emotionally resonant films.',
                   'Furthermore, "Interstellar" has had a lasting impact on pop culture, influencing subsequent films in the sci-fi genre. Its exploration of themes like global warming and humanity\'s future has sparked discussions beyond cinema. For instance, scenes depicting Earth\'s environmental collapse vividly illustrate these themes, contributing to a broader cultural dialogue about our planet\'s sustainability and our place in the universe. This multifaceted influence underscores "Interstellar"\'s significance as both an artistic achievement and a catalyst for scientific curiosity.'],
               "## 4. Critical Reception of 'Interstellar'": '',
               "### 4.1. Awards Won by 'Interstellar'": [
                   'Christopher Nolan\'s "Interstellar" has earned numerous accolades for its visionary storytelling and groundbreaking visual effects. The film captivated audiences by exploring complex scientific concepts like time dilation and alternate dimensions, sparking interest among scientists as well. Notably, "Interstellar" won the Saturn Award for Best Science Fiction Film in 2015, recognizing its innovative approach to the genre. It was also nominated for five Academy Awards, including Best Visual Effects and Best Original Score, highlighting its impact on cinematic artistry. The emotional depth of the story, particularly the father-daughter relationship between Cooper and Murph, resonated deeply with critics and audiences alike. This emotional core, combined with its scientific rigor, placed "Interstellar" among the most critically acclaimed films of its time. Although some critics found issues with dialogue and character development, the film\'s ambition and scope have been widely praised. The American Film Institute named "Interstellar" one of the Top 10 Films of 2014, further cementing its status as a modern classic in science fiction cinema.'],
               '### 4.2. Notable Reviews and Criticisms': [
                   'The critical reception of "Interstellar" has been a mixed bag, reflecting the film\'s ambitious scope and complex narrative. Scott Foundas of Variety praises the film for its "visually and conceptually audacious" nature, noting its personal touch compared to Nolan\'s previous works. Claudia Puig of USA Today appreciates the visual spectacle and powerful themes but finds the dialogue "dull" and parts of the space vessel scenes "tedious." David Stratton commends the film\'s ambition and effects but criticizes the sound for being too loud, making some dialogue inaudible. James Berardinelli calls "Interstellar" an "amazing achievement," highlighting its balance between big-budget science fiction and a simple tale of love and sacrifice. He ranks it as the best film of 2014, emphasizing its status as a "real science fiction" rather than a watered-down version typical in Hollywood. Quentin Tarantino admires the film\'s grand vision, comparing it to works by Tarkovsky or Malick, which is unusual for a science fiction adventure movie. Oliver Gettell summarizes that critics generally agree on "Interstellar" being an entertaining, emotional, and thought-provoking sci-fi saga, despite its occasional clunkiness and sentimentality. James Dyer of Empire awards it five stars, describing it as "brainy, barmy, and beautiful to behold." Dave Calhoun of Time Out London also gives it five stars, appreciating its bold and beautiful cosmic adventure with surreal and dreamlike elements. Richard Roeper praises the film\'s visuals and overriding message about love as one of the most beautiful films he had ever seen. Tim Robey considers it agonizingly close to a masterpiece due to its conceptual boldness and deep-digging intelligence. Todd McCarthy finds the epic engrossing despite mixed results in balancing intimate human emotions with cosmic speculation. Jake Coyle highlights the film\'s big-screen grandeur but notes some clunky dialogue, describing it as an absurd endeavor that is one of the most sublime movies of the decade. Scott Mendelson lists it among 2014\'s most disappointing films due to issues like lack of flow, loss of momentum post-climax, clumsy sound mixing, and thin characters. Matt Zoller Seitz appreciates its impressive nature but has quibbles about Nolan\'s excessive dialogue lacking sense of composition.'],
               '## 5. Box Office Performance and Audience Reception': [
                   '"Interstellar" faced a unique challenge at the box office due to its serious-minded science-fiction approach, which differed significantly from the typical blockbuster fare. Unlike films like "The Dark Knight Rises," which draw massive opening weekend crowds, "Interstellar" attracted an older audience, with 75% of its opening weekend viewers being over the age of 25. This demographic shift influenced its box office performance, as it did not achieve the immediate stratospheric success that Hollywood often anticipates. However, this does not diminish its significance; rather, it underscores the film\'s ability to engage a more reflective and mature audience.',
                   'Critics were divided on "Interstellar." Some praised its ambitious scope and visual spectacle, while others criticized its dialogue and pacing. For instance, Roger Ebert commended the film\'s "visually stunning sequences," whereas Peter Travers found the dialogue "stilted and unconvincing." This mixed reception mirrored the film\'s complex narrative and thematic depth, sparking extensive debate within film circles and beyond. Despite these varying opinions, "Interstellar" managed to maintain a strong hold at the box office, demonstrating that ambitious films can build their revenues methodically over time rather than relying solely on explosive opening weekends.',
                   'The film\'s critical reception also had implications for its long-term revenue potential. While it may not have been an immediate Oscars juggernaut as some predicted, its impact on audiences ensured that it remained a topic of discussion and analysis long after its release. This sustained interest contributed to its overall success, proving that films like "Interstellar" can achieve lasting cultural impact through thoughtful storytelling and innovative filmmaking techniques.'],
               "## 6. Conclusion: Why 'Interstellar' is a Significant Film in Modern Cinema": [
                   '"Interstellar" is a significant film in modern cinema, renowned not only for its groundbreaking visual effects and scientific accuracy but also for its profound exploration of human emotions and the mysteries of the universe. The film\'s narrative complexity, driven by Christopher Nolan\'s meticulous direction, invites audiences to ponder the themes of love, time, and human resilience. For instance, the relationship between Cooper (played by Matthew McConaughey) and his daughter Murph serves as a poignant example of these themes. McConaughey\'s powerful portrayal of Cooper, a man torn between his mission to save humanity and his deep love for Murph, anchors the emotional core of the story. This emotional depth is further enriched by Hans Zimmer\'s haunting score, which complements both the film\'s grand scale and intimate moments.',
                   'Transitioning smoothly to its scientific aspects, "Interstellar" benefits from collaboration with theoretical physicist Kip Thorne, adding a layer of authenticity that elevates it beyond conventional science-fiction fare. Concepts like wormholes and time dilation are depicted with such precision that they not only entertain but also educate viewers about the possibilities of interstellar travel. This blend of cutting-edge science and human drama makes "Interstellar" a cinematic experience that leaves a lasting impact on its audience.',
                   'Furthermore, "Interstellar" has had a profound influence on both science-fiction cinema and popular culture. Its exploration of complex scientific ideas within a deeply human story has inspired new generations of filmmakers to push the boundaries of what sci-fi can achieve. The film has also reignited public interest in space exploration, highlighting the importance of scientific discovery and our collective curiosity about the cosmos. In conclusion, "Interstellar" stands as a testament to cinema\'s power to inspire, challenge, and touch our deepest emotions through an unforgettable journey through space and time. The film\'s ambitious scope in exploring complex scientific theories alongside emotional depth sets a new standard for cinematic storytelling. Christopher Nolan\'s meticulous direction combines with groundbreaking visual effects and an evocative score by Hans Zimmer to create an immersive experience that resonates deeply with audiences. Despite mixed critical reception, "Interstellar" has achieved lasting cultural impact through its innovative approach to blending science fiction with profound human emotion. This blend not only inspires cinema but also real-world space exploration efforts. As a result, "Interstellar" remains a landmark film that continues to influence both filmmakers and audiences alike in their quest to understand the mysteries of the cosmos and our own existence within it.']}
    summary = ['"Interstellar" is a genre-defying sci-fi epic that blends science, emotion, and profound storytelling.',
               'Output:\nChristopher Nolan\'s "Interstellar" combines visionary sci-fi and profound human drama, blending scientific authenticity with emotional depth to create a thought-provoking cinematic masterpiece.',
               '"Interstellar," released on November 7, 2014, is a profound sci-fi film exploring love, sacrifice, and human resilience through a mission to find a new habitable planet.',
               '"Interstellar" is a profound exploration of human connection and existence, blending science with deep emotion.',
               '"Interstellar" is a groundbreaking sci-fi film that blends complex storytelling, emotional depth, and scientific accuracy, leaving a lasting cultural impact.',
               '"Interstellar" is a critically acclaimed sci-fi film known for its innovative storytelling, groundbreaking effects, and emotional depth.',
               'Critics have mixed opinions on "Interstellar," praising its ambitious scope and visual spectacle while criticizing its dialogue and pacing.',
               '"Interstellar" attracted an older audience, achieved lasting cultural impact through thoughtful storytelling and innovative filmmaking despite mixed critical reception.',
               '"Interstellar" is a groundbreaking sci-fi film that blends scientific accuracy with profound human emotion, inspiring both cinema and space exploration.',
               '"Interstellar" is a groundbreaking sci-fi film that blends complex science with profound human themes, significantly impacting both cinema and culture.']

    content = Add_transition(outline, content)
    print("cool!")

